seed: 42

data:
    prod: True
    mag:
        query_values: ['biorxiv']
        entity_name: 'J.JN'
        metadata: ["Id", "Ti", "AA.AfId", "AA.AfN", "AA.AuId", "AA.DAuN", "AA.S", "CC", "D", "F.DFN", "F.FId", "J.JId", "J.JN", "Pt", "RId", "Y", "DOI", "PB", "BT", "IA", "C.CN", "C.CId"]

umap:
    n_neighbors: 5
    n_components: 2
    metric: 'cosine'
    min_dist: .01

country_collaboration:
    year: '2013'

svd:
    n_components: 500

topic_filter:
    levels: [1]
    percentiles: [75]

gender_diversity:
    threshold: .75

metrics:
    year: '2013'
    paper_count_low: 5
    paper_count_high: 40 
    fos_count: 10

affilations:
    non_profit: ['park centre for mental health', 'university', 'foundation', 'institution', 'universidade', 'institute', 'commission', 'agency', 'department', 'council', 'college', 'ministry', 'universidad', 'school', 'international centre', 'universiti', 'hospital', 'medical center', 'united states fish and wildlife service', 'centre', 'center', 'laboratory', 'universiteti', 'kantonsspital st gallen', 'infirmary', 'centro', 'museum', 'academy', 'istituto', 'national association', 'conservation trust', 'instituto', 'ezemvelo kzn wildlife', 'nhs trust', 'universite', 'society', 'united states office of research integrity', 'missouri botanical garden', 'nhs lothian', 'zurcher fachhochschule', 'administration', 'ecole', 'congressional research service', 'universitat', 'bureau', 'clinical trial service unit', 'fachhochschule lubeck', 'umass memorial health care', 'penn state abington', 'federation', 'office of', 'nhs greater glasgow and clyde', 'intelligence and national security alliance', 'rambam health care campus', 'cancer research uk', 'carolinas healthcare system', 'arthritis research uk', 'vancouver coastal health', 'red cross', 'commonwealth scientific and industrial', 'institut', 'academia', 'association', 'fondazione', 'faculty', 'escuela', 'facultad de filosofia y letras', 'coral reef alliance', 'fundacion', 'queensland health', 'jamia millia islamia', 'polytechnic', 'united states forest service', 'national ecological observatory network', 'national guard health affairs', 'geoscience australia', 'statistics canada', 'health service executive', 'district', 'national marrow donor program', 'junta of andalusia', 'american board of legal medicine', 'geological survey of denmark and greenland', 'australia bioinformatics resource', 'south african weather service', 'scottish national blood transfusion service', 'pancreatic cancer action network', 'va palo alto healthcare system', 'swiss federal laboratories for materials', 'defence research and development organisation', 'conservation international', 'european union','clalit health services', 'comision nacional', 'departamento', 'office national', 'rajiv gandhi proudyogiki vishwavidyalaya', 'nhs blood and transplant', 'european molecular biology organization', 'facultad', 'united nations environment programme', 'national health service', 'rochester general health system', 'bundesanstalt fur materialforschung und prufung','drugs for neglected diseases initiative', 'gundersen health system', 'fisheries and oceans canada', 'food safety and inspection service', 'civil aviation authority of singapore', 'union of concerned scientists', 'california state water resources control board', 'wright patterson air force base', 'bioversity international', 'marine scotland', 'qatar national library', 'american geophysical union', 'cherokee nation', 'national radio astronomy observatory', 'asia pacific economic cooperation', 'the leprosy mission international', 'kenya wildlife service', 'australian taxation office', 'breast cancer now', 'pan american health organization', 'united states public health service', 'butterfly conservation', 'king abdulaziz medical city']
